name: Rest Assured CI CD

# Disparadores del flujo de trabajo
on:
  # En cada pusheo de codigo
  push:
    branches:
      - main
  # En cada pull request de codigo
  pull_request:
    branches:
      - main

# Definir los jobs
jobs:
  build:
    # Se correra en una maquina virtual ubuntu comun
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio pasando URL
      - name: https://github.com/panaderodiaz98/restAssured.git
        uses: actions/checkout@v3

      # Paso 2: Configurar JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      # Paso 3: Configurar caché para dependencias de Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Paso 4: Ejecutar pruebas y generar resultados de Allure
      - name: Run tests with Maven
        run: mvn clean test

      - name: Generate Allure Report
        run: |
          mvn allure:report
          mvn allure:aggregate
          
      # Paso 5: Adjuntar el reporte de Allure como artefacto
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
